<template>
    <div class="bottom-view">
        <div class="bottom-header">
            <div class="bottom-header-item">
                <div class="">12</div>
            </div>
            <div class="bottom-header-item"></div>
            <div class="bottom-header-item"></div>
        </div>
        <div class="bottom-footer">
            <div class="code-box">
                <div class="code-line">
                    <div class="item">1</div>
                    <div class="item">; GCODE Generated by cam.openbuilds.com on 2021-08-23</div>
                </div>
                <div class="code-line">
                    <div class="item">199999</div>
                    <div class="item">G21 ; mm-mode</div>
                </div>
                <div class="code-line">
                    <div class="item">200000</div>
                    <div class="item">G21 ; mm-mode</div>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import {defineComponent, onBeforeMount, onMounted, onBeforeUnmount, onUnmounted} from "vue";
import * as icons from "@element-plus/icons";
export default defineComponent({
    name: "BottomConsole",
    emits: [],
    props: ["cnc"],
    components: {},
    setup(props, context) {

        onBeforeMount(() => {});

        onMounted(() => {});

        onBeforeUnmount(() => {});

        onUnmounted(() => {});

        return {
            props,
            icons
        }
    }
});
</script>

<style scoped>
.bottom-view{
    width: 100%;
    height: 100%;
}
.bottom-view .bottom-header{
    width: 100%;
    height: 40px;
    background-color: rgba(43, 45, 48, .5);
    border-bottom: solid 1px rgba(30, 31, 34, .8);
}
.bottom-view .bottom-header .bottom-header-item{
    width: 33.33%;
    height: 40px;
    display: inline-block;
    vertical-align: top;
    padding: 5px;
}
.bottom-view .bottom-footer{
    width: 100%;
    height: calc(100% - 40px);
    overflow-y: auto;
}
.bottom-view .bottom-footer .code-box{
    width: 100%;
}
.bottom-view .bottom-footer .code-box .code-line{
    width: 100%;
    height: 24px;
    line-height: 24px;
    color: #666666;
}
.bottom-view .bottom-footer .code-box .code-line:hover{
    color: #999999;
}
.bottom-view .bottom-footer .code-box .code-line .item{
    width: auto;
    height: 24px;
    display: inline-block;
    vertical-align: top;
}
.bottom-view .bottom-footer .code-box .code-line .item:first-child{
    width: 50px;
    color: #666666;
    text-align: right;
    padding-right: 5px;
}
.bottom-view .bottom-footer .code-box .code-line .item:last-child{
    width: calc(100% - 50px);
}
</style>
