// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeviceRequest(arg1, arg2, arg3, arg4) {
  return window['go']['StartWindows']['Api']['DeviceRequest'](arg1, arg2, arg3, arg4);
}

export function DeviceUpload(arg1, arg2, arg3, arg4) {
  return window['go']['StartWindows']['Api']['DeviceUpload'](arg1, arg2, arg3, arg4);
}

export function GetPlatform() {
  return window['go']['StartWindows']['Api']['GetPlatform']();
}

export function OpenFile(arg1, arg2, arg3) {
  return window['go']['StartWindows']['Api']['OpenFile'](arg1, arg2, arg3);
}

export function ServiceRequest(arg1, arg2, arg3, arg4) {
  return window['go']['StartWindows']['Api']['ServiceRequest'](arg1, arg2, arg3, arg4);
}
